# POR: DANILO COSTA
# UNIVERSIDADE ESTADUAL DO MARANHÃO
# GRADUANDO EM ENGENHARIA DE COMPUTAÇÃO

f = float(input('DIGITE A TEMPERATURA EM GRAUS FARENHEIT:'))
c = (5 * (f-32) / 9)
print('TEMPERATURA EM CELSIUS: {}'.format(c))