# POR: DANILO COSTA
# UNIVERSIDADE ESTADUAL DO MARANHÃO
# GRADUANDO EM ENGENHARIA DE COMPUTAÇÃO

n = float(input('DIGITE UM NUMERO: '))

if n == int(n):
    print('NUMERO INTEIRO')
else:
    print('NUMERO DECIMAL')